<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Authors>Ludovit Scholtz</Authors>
		<Company>Scholtz And Co</Company>
		<PackageProjectUrl>https://github.com/scholtz/BiatecRouterConnector</PackageProjectUrl>
		<RepositoryUrl>https://github.com/scholtz/BiatecRouterConnector</RepositoryUrl>
		<NeutralLanguage>en-US</NeutralLanguage>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<Version>1.0.0.$([System.DateTime]::Now.ToString(yyyyMMddHH))</Version>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageTags>algorand,trading,dex swap,dex aggregator,trade,arc14,arc76,dex,aggregator,algo,swap</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Algorand4" Version="4.4.1.2026010317" />
		<PackageReference Include="AlgorandARC76Account" Version="1.1.0" />
		<PackageReference Include="NSwag.MSBuild" Version="14.5.0" PrivateAssets="all" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

	<PropertyGroup>
		<NSwagGenerateExceptionClasses>true</NSwagGenerateExceptionClasses>
	</PropertyGroup>

	<Target Name="GenerateBiatecRouterApiClient" BeforeTargets="Compile">
		<Exec Command="dotnet --roll-forward LatestMajor &quot;$(PkgNSwag_MSBuild)\tools\Net90\dotnet-nswag.dll&quot; run &quot;$(MSBuildProjectDirectory)\nswag.json&quot; /variables:Configuration=$(Configuration)" />
	</Target>

	<ItemGroup>
		<Compile Include="obj\**\BiatecRouterApiClient.cs" Link="Generated\BiatecRouterApiClient.cs" Visible="false" />
	</ItemGroup>

	<ItemGroup>
		<None Update="README.md">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

</Project>
